{% set name = "7zip" %}
{% set version = "24.09" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/sevenzip/7-Zip/{{ version }}/7z{{ version.replace('.', '') }}-src.7z
  sha256: a33569eed0ce628fb9ceb9f46ac257d3f36b3966471667e65ba01878673c9faa

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  run_constrained:
    - 7za <0.0.0a

test:
  imports:

  commands:
    - 7zg.exe
    - 7za.exe
    - 7zr.exe

about:
  home: https://www.7-zip.org/
  license: LGPL-2.1-or-later AND LGPL-2.1-or-later WITH unRAR-restriction
  license_family: LGPL
  license_file:
    - LICENSE.txt
    - UNRAR_LICENSE.txt
  description: |
    7-Zip is a file archiver with a high compression ratio.
  summary: 7-Zip is a file archiver with a high compression ratio.
  dev_url: https://sourceforge.net/p/sevenzip/
  doc_url: https://www.7-zip.org
extra:
  recipe-maintainers:
    - wolfv
