{% set name = "7zip" %}
{% set version = "25.01" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/sevenzip/7-Zip/{{ version }}/7z{{ version.replace('.', '') }}-src.7z
  sha256: 2aed39b8f1238464475e9de7dda169a5e873a1dc8bbf4f664b943eaba5620181

build:
  number: 1
  skip: true  # [not win or win32]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  run_constrained:
    - 7za <0.0.0a

test:
  commands:
    - 7z.exe
    - 7za.exe
    - 7zr.exe

about:
  home: https://www.7-zip.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file:
    - LICENSE.txt
    - UNRAR_LICENSE.txt
  description: |
    7-Zip is a file archiver with a high compression ratio.
  summary: 7-Zip is a file archiver with a high compression ratio.
  dev_url: https://sourceforge.net/p/sevenzip/
  doc_url: https://www.7-zip.org
extra:
  recipe-maintainers:
    - wolfv